import './scripts/navLinks.js';
import './scripts/projects.js';
import './scripts/scrollingAnimations.js';
import './scripts/scrollingEvents.js';
import './scripts/skills.js';
import './scripts/menu.js';
import './scripts/socials.js';
import './scripts/lang.js';
import './scripts/theme.js';